force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>adventure</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/objects/Movie__c/fields/imageUrl__c.field-meta.xml
<CustomField>
    <fullName>imageUrl__c</fullName>
    <label>imageUrl</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/classes/moviesController.cls
public with sharing class moviesController {

@AuraEnabled
public static void saveMovie(Movie__c movie){
try {
    insert movie;
}
 catch(Exception e){
    throw new AuraHandledException(e.getMessage());
 }
}

@AuraEnabled
public static List <Movie__c> retrieveMovies(){

    List <Movie__c> listMovies = new List<Movie__c> (
        [SELECT Id, Name, Description__c,Category__c, Release_date__c, imageUrl__c,Rating__c FROM Movie__c ]
    );
    return listMovies;
}
}